version: "3.9"

services:
  canal-denuncia:
    build: .
    container_name: canal-denuncia-app
    ports:
      - "7070:7070"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=7070
    restart: unless-stopped
